<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Nowy folder1\**" />
    <Compile Remove="Nowy folder\**" />
    <EmbeddedResource Remove="Nowy folder1\**" />
    <EmbeddedResource Remove="Nowy folder\**" />
    <None Remove="Nowy folder1\**" />
    <None Remove="Nowy folder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Calculator\Validators1.cs" />
  </ItemGroup>

</Project>
